#³¢®Ë¸Û ¸ê¤u¤T 406410114
SHELL = /bin/bashr
CC = g++
CFLAGS = -o
SRC!= ls Grade*.cpp Grade.h
OBJ = ${SRC:.cpp=.o}
EXE = a.out


$(EXE):$(SRC)
	$(CC) $(CFLAGS) $(EXE) $(SRC)



  
clean:
	rm  -f $(EXE) 
  
 
 

